services:
  Dbp\Relay\BasePersonConnectorLdapBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BasePersonConnectorLdapBundle\Service\LDAPApi:
    autowire: true
    autoconfigure: true
    calls:
      - setPersonCache: [ '@dbp.relay.base_person_connector_ldap.cache.auth_person' ]

  Dbp\Relay\BasePersonConnectorLdapBundle\Service\LDAPPersonProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BasePersonConnectorLdapBundle\EventSubscriber\PersonEventSubscriber:
    autowire: true
    autoconfigure: true

  Dbp\Relay\BasePersonBundle\API\PersonProviderInterface:
    '@Dbp\Relay\BasePersonConnectorLdapBundle\Service\LDAPPersonProvider'


  dbp.relay.base_person_connector_ldap.cache.auth_person:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 360 }
