services:
  Dbp\Relay\BasePersonConnectorLdapBundle\Service\:
    resource: '../../Service'
    autowire: true
    autoconfigure: true

  Dbp\Relay\BasePersonBundle\API\PersonProviderInterface:
    '@Dbp\Relay\BasePersonConnectorLdapBundle\Service\BasePersonConnectorLdap'

  Dbp\Relay\AuthBundle\API\UserRolesInterface:
    '@Dbp\Relay\BasePersonConnectorLdapBundle\Service\CustomUserRoles'

  Dbp\Relay\BasePersonConnectorLdapBundle\API\LDAPApiProviderInterface:
    '@Dbp\Relay\BasePersonConnectorLdapBundle\Service\DummyLDAPApiProvider'
